let courseData =  [
        {
           'code':'HKCPM/01/22',
		   'name':'認別長者住戶正常老化',
		   'field':'非核心',
		   'cate':'類別一',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'21/3/2024',
		   'time':'19:00 至 21:00',
		   'location':'香港鴨脷洲利東邨東昌樓地下101-107室',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/02/22',
		   'name':'掌握與長者及護老者住戶溝通',
		   'field':'非核心',
		   'cate':'類別一',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'20/6/2024',
		   'time':'19:00 至 21:00',
		   'location':'香港鴨脷洲利東邨東昌樓地下101-107室',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/03/22',
		   'name':'促進長者住戶進行有意義活動',
		   'field':'非核心',
		   'cate':'類別一',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'19/9/2024',
		   'time':'19:00 至 21:00',
		   'location':'香港鴨脷洲利東邨東昌樓地下101-107室',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/04/22',
		   'name':'共建長者友善屋苑',
		   'field':'非核心',
		   'cate':'類別三',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'19/12/2024',
		   'time':'19:00 至 21:00',
		   'location':'香港鴨脷洲利東邨東昌樓地下101-107室',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/05/22',
		   'name':'8分鐘驗漏水樓',
		   'field':'核心',
		   'cate':'類別四',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'20/5/2024',
		   'time':'19:00 至 21:00',
		   'location':'香港金鐘金鐘道95號統一中心5樓',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/06/22',
		   'name':'8分鐘驗漏水樓',
		   'field':'核心',
		   'cate':'類別二',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'19/8/2024',
		   'time':'19:00 至 21:00',
		   'location':'香港金鐘金鐘道95號統一中心5樓',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/07/22',
		   'name':'Professional Mediation Specialist Certification Training Course – Property and Building Management Mediation Specialist',
		   'field':'核心',
		   'cate':'類別五',
		   'type':'正式',
		   'learningCate':'課程（包括全日制、兼讀制、遙距及網上課程）',
		   'online':'實體',
		   'date':'4/5/2024',
		   'time':'18:30 至 21:30',
		   'location':'5/F, West Wing, Justice Place, 11 Ice House Street, Central, Hong Kong',
		   'aHour':'12',
		   'pHour':'12',
		   'attendance':'20'
        },{
           'code':'HKCPM/08/22',
		   'name':'Professional Mediation Specialist Certification Training Course – Property and Building Management Mediation Specialist',
		   'field':'核心',
		   'cate':'類別六',
		   'type':'正式',
		   'learningCate':'課程（包括全日制、兼讀制、遙距及網上課程）',
		   'online':'實體',
		   'date':'10//8/2024',
		   'time':'18:30 至 21:30',
		   'location':'5/F, West Wing, Justice Place, 11 Ice House Street, Central, Hong Kong',
		   'aHour':'12',
		   'pHour':'12',
		   'attendance':'20'
        },{
           'code':'HKCPM/09/22',
		   'name':'Professional Mediation Specialist Certification Training Course – Property and Building Management Mediation Specialist',
		   'field':'核心',
		   'cate':'類別五',
		   'type':'正式',
		   'learningCate':'課程（包括全日制、兼讀制、遙距及網上課程）',
		   'online':'實體',
		   'date':'7/11/2024',
		   'time':'18:30 至 21:30',
		   'location':'5/F, West Wing, Justice Place, 11 Ice House Street, Central, Hong Kong',
		   'aHour':'12',
		   'pHour':'12',
		   'attendance':'20'
        },{
           'code':'HKCPM/10/22',
		   'name':'後疫情時代 -- 環球購物中心的潮流與創新',
		   'field':'核心',
		   'cate':'類別四',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'網上',
		   'date':'5/5/2024',
		   'time':'19:00 至 21:00',
		   'location':'',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/11/22 ',
		   'name':'房地產技術、金融技術、區塊鍊和 ESG(環境、社會與管治）的新時代 ',
		   'field':'核心',
		   'cate':'類別三',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'網上',
		   'date':'18/8/2024',
		   'time':'19:00 至 21:00',
		   'location':'',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },{
           'code':'HKCPM/14/22 ',
		   'name':'物業管理從業員在處理法團面對的訴訟及大維修問題的竅門, 公關及書寫技巧',
		   'field':'核心',
		   'cate':'類別二',
		   'type':'正式',
		   'learningCate':'講座／會議／研討會／工作坊',
		   'online':'實體',
		   'date':'6/8/2024',
		   'time':'19:00 至 21:00',
		   'location':'',
		   'aHour':'2',
		   'pHour':'2',
		   'attendance':'20'
        },
      
    ]


export { courseData };